name: Update Gist from Facebook Links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  process_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Make script executable
        run: chmod +x scripts/process_links.sh

      - name: Run link processor script
        run: ./scripts/process_links.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
